# Generated by Django 4.0.2 on 2022-03-11 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.DecimalField(decimal_places=0, max_digits=6)),
                ('gender', models.CharField(max_length=100)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=6)),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=6)),
                ('advance', models.DecimalField(decimal_places=0, max_digits=6)),
                ('due', models.DecimalField(decimal_places=0, max_digits=6)),
                ('role', models.CharField(default='Patient', max_length=100)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected', to='diagnostic.test')),
            ],
        ),
    ]
